"""add portfolio stages snapshots and team models

Revision ID: 1a0afd5acf88
Revises: b7049941e0bf
Create Date: 2026-10-08 14:27:17.608026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0afd5acf88'
down_revision: Union[str, Sequence[str], None] = 'b7049941e0bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_stage_definitions_id'), 'stage_definitions', ['id'], unique=False)
    op.create_table('project_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('percent_complete', sa.Float(), nullable=False),
    sa.Column('percent_work_complete', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('baseline_finish', sa.Date(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('baseline_cost', sa.Float(), nullable=False),
    sa.Column('baseline_budget', sa.Float(), nullable=False),
    sa.Column('budget_cost', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_snapshots_id'), 'project_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_project_snapshots_project_id'), 'project_snapshots', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_snapshots_recorded_at'), 'project_snapshots', ['recorded_at'], unique=False)
    op.create_table('project_stage_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DONE', 'NOT_DONE', 'NOT_APPLICABLE', name='stagestatusenum'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_stage_statuses_id'), 'project_stage_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_project_stage_statuses_project_id'), 'project_stage_statuses', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_stage_statuses_stage_id'), 'project_stage_statuses', ['stage_id'], unique=False)
    op.create_table('project_team_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_team_resources_id'), 'project_team_resources', ['id'], unique=False)
    op.create_index(op.f('ix_project_team_resources_project_id'), 'project_team_resources', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_team_resources_resource_id'), 'project_team_resources', ['resource_id'], unique=False)
    op.add_column('projects', sa.Column('start_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'start_date')
    op.drop_index(op.f('ix_project_team_resources_resource_id'), table_name='project_team_resources')
    op.drop_index(op.f('ix_project_team_resources_project_id'), table_name='project_team_resources')
    op.drop_index(op.f('ix_project_team_resources_id'), table_name='project_team_resources')
    op.drop_table('project_team_resources')
    op.drop_index(op.f('ix_project_stage_statuses_stage_id'), table_name='project_stage_statuses')
    op.drop_index(op.f('ix_project_stage_statuses_project_id'), table_name='project_stage_statuses')
    op.drop_index(op.f('ix_project_stage_statuses_id'), table_name='project_stage_statuses')
    op.drop_table('project_stage_statuses')
    op.drop_index(op.f('ix_project_snapshots_recorded_at'), table_name='project_snapshots')
    op.drop_index(op.f('ix_project_snapshots_project_id'), table_name='project_snapshots')
    op.drop_index(op.f('ix_project_snapshots_id'), table_name='project_snapshots')
    op.drop_table('project_snapshots')
    op.drop_index(op.f('ix_stage_definitions_id'), table_name='stage_definitions')
    op.drop_table('stage_definitions')
    # ### end Alembic commands ###
