"""add last_updated_by and last_updated_at to projects

Revision ID: 3b61355fb11d
Revises: fcbabcfea95e
Create Date: 2026-10-09 14:40:07.251975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b61355fb11d'
down_revision: Union[str, Sequence[str], None] = 'fcbabcfea95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('last_updated_by', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('last_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'last_updated_at')
    op.drop_column('projects', 'last_updated_by')
    # ### end Alembic commands ###
