"""initial master data schema

Revision ID: b7049941e0bf
Revises: 
Create Date: 2026-10-08 14:20:02.754848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7049941e0bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=False),
    sa.Column('is_base_calendar', sa.Boolean(), nullable=False),
    sa.Column('base_calendar_uid', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendars_id'), 'calendars', ['id'], unique=False)
    op.create_table('custom_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('entity', sa.Enum('TASK', 'RESOURCE', 'PROJECT', name='customfieldentityenum'), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'COST', 'DATE', 'FLAG', name='customfieldtypeenum'), nullable=False),
    sa.Column('slot_number', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.String(length=32), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('default_value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_fields_id'), 'custom_fields', ['id'], unique=False)
    op.create_table('calendar_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('working', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_exceptions_calendar_id'), 'calendar_exceptions', ['calendar_id'], unique=False)
    op.create_index(op.f('ix_calendar_exceptions_from_date'), 'calendar_exceptions', ['from_date'], unique=False)
    op.create_index(op.f('ix_calendar_exceptions_id'), 'calendar_exceptions', ['id'], unique=False)
    op.create_table('field_lookup_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('custom_field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_lookup_values_custom_field_id'), 'field_lookup_values', ['custom_field_id'], unique=False)
    op.create_index(op.f('ix_field_lookup_values_id'), 'field_lookup_values', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_guid', sa.String(length=64), nullable=False),
    sa.Column('erp_number', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('budget_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_erp_number'), 'projects', ['erp_number'], unique=True)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_owner'), 'projects', ['owner'], unique=False)
    op.create_index(op.f('ix_projects_project_guid'), 'projects', ['project_guid'], unique=True)
    op.create_table('resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(length=64), nullable=False),
    sa.Column('ad_upn', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('resource_type', sa.Enum('WORK', 'MATERIAL', 'COST', name='resourcetypeenum'), nullable=False),
    sa.Column('resource_kind', sa.Enum('NAMED', 'GENERIC', name='resourcekindenum'), nullable=False),
    sa.Column('is_generic', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('base_calendar_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['base_calendar_id'], ['calendars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_ad_upn'), 'resources', ['ad_upn'], unique=False)
    op.create_index(op.f('ix_resources_department'), 'resources', ['department'], unique=False)
    op.create_index(op.f('ix_resources_email'), 'resources', ['email'], unique=False)
    op.create_index(op.f('ix_resources_guid'), 'resources', ['guid'], unique=True)
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_is_active'), 'resources', ['is_active'], unique=False)
    op.create_index(op.f('ix_resources_name'), 'resources', ['name'], unique=False)
    op.create_table('rate_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('rate_table', sa.Enum('A', 'B', 'C', 'D', 'E', name='ratetableenum'), nullable=False),
    sa.Column('standard_rate', sa.Float(), nullable=False),
    sa.Column('overtime_rate', sa.Float(), nullable=False),
    sa.Column('cost_per_use', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('rates_to', sa.Date(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_periods_effective_date'), 'rate_periods', ['effective_date'], unique=False)
    op.create_index(op.f('ix_rate_periods_id'), 'rate_periods', ['id'], unique=False)
    op.create_index(op.f('ix_rate_periods_resource_id'), 'rate_periods', ['resource_id'], unique=False)
    op.create_table('resource_field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('custom_field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_field_values_custom_field_id'), 'resource_field_values', ['custom_field_id'], unique=False)
    op.create_index(op.f('ix_resource_field_values_id'), 'resource_field_values', ['id'], unique=False)
    op.create_index(op.f('ix_resource_field_values_resource_id'), 'resource_field_values', ['resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_field_values_resource_id'), table_name='resource_field_values')
    op.drop_index(op.f('ix_resource_field_values_id'), table_name='resource_field_values')
    op.drop_index(op.f('ix_resource_field_values_custom_field_id'), table_name='resource_field_values')
    op.drop_table('resource_field_values')
    op.drop_index(op.f('ix_rate_periods_resource_id'), table_name='rate_periods')
    op.drop_index(op.f('ix_rate_periods_id'), table_name='rate_periods')
    op.drop_index(op.f('ix_rate_periods_effective_date'), table_name='rate_periods')
    op.drop_table('rate_periods')
    op.drop_index(op.f('ix_resources_name'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_active'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_guid'), table_name='resources')
    op.drop_index(op.f('ix_resources_email'), table_name='resources')
    op.drop_index(op.f('ix_resources_department'), table_name='resources')
    op.drop_index(op.f('ix_resources_ad_upn'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_projects_project_guid'), table_name='projects')
    op.drop_index(op.f('ix_projects_owner'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_erp_number'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_field_lookup_values_id'), table_name='field_lookup_values')
    op.drop_index(op.f('ix_field_lookup_values_custom_field_id'), table_name='field_lookup_values')
    op.drop_table('field_lookup_values')
    op.drop_index(op.f('ix_calendar_exceptions_id'), table_name='calendar_exceptions')
    op.drop_index(op.f('ix_calendar_exceptions_from_date'), table_name='calendar_exceptions')
    op.drop_index(op.f('ix_calendar_exceptions_calendar_id'), table_name='calendar_exceptions')
    op.drop_table('calendar_exceptions')
    op.drop_index(op.f('ix_custom_fields_id'), table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index(op.f('ix_calendars_id'), table_name='calendars')
    op.drop_table('calendars')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
